python_library(
  name='pbase',
  dependencies=[
    'infrastructure/src/main/python/pbase/papp',
    'infrastructure/src/main/python/pbase/ptext',
    'infrastructure/src/main/python/pbase/pnn/tensorflow',
    'infrastructure/src/main/python/pbase/pnn/pytorch',
  ],
  provides=setup_py(
    name='pbase',
    version='0.0.1',
    author='Peng Shi',
    author_email='peng_shi@outlook.com',
    description='framework for deep learning applications',
    url='https://github.com/Impavidity/pbase',
    license='MIT'
  )
)