jvm_binary(name = "tdbquery",
  source = 'TDBQuery.java',
  main = 'botafogo.TDBQuery',
  dependencies = [
    '3rdparty/jvm:jena',
    '3rdparty/jvm:log4j',
    '3rdparty/jvm:args4j',
    'infrastructure/src/main/java:config',
  ],
)
