jvm_binary(name = "linking",
  source = 'Linking.java',
  main = 'zoo.linking.Linking',
  dependencies = [
    'infrastructure/src/main/java/pbase/ptext',
    '3rdparty/jvm:tensorflow',
    '3rdparty/jvm:guava',
    '3rdparty/jvm:anserini',
  ],
)
