jvm_binary(name = "ner",
  source = 'NER.java',
  main = 'zoo.ner.NER',
  dependencies = [
    'infrastructure/src/main/java/pbase/ptext',
    '3rdparty/jvm:tensorflow',
    '3rdparty/jvm:guava',
    '3rdparty/jvm:anserini',
  ],
)