python_library(
    sources = ["*.py"],
    dependencies = [
        '3rdparty/python:six',
        '3rdparty/python:numpy',
        '3rdparty/python:tensorflow',
        '3rdparty/python:tqdm',
    ],
)